// FIX: StadiumId column is now hidden in the grid (was visible raw FK).
// FIX: txtid is no longer passed to StadiumRepository.Add() — ID is auto-generated by DB.
// FIX: Success MessageBoxes added to Add/Update/Delete with icons.
// FIX: Validation added before int.Parse in btnAdd_Click.
// FIX: Removed unused 'using System.Xml.Linq' import.
// NEW: Calls UIHelper for styling and SetPlaceholder.
// FIX: LoadStadiums duplicate call on Form_Load removed (constructor already calls it).

using EPL_DBMS.DataAccess;
using EPL_DBMS.Models;
using EPL_DBMS.Utils;
using System;
using System.Windows.Forms;

namespace EPL_DBMS.Forms
{
    public partial class StadiumsForm : Form
    {
        public StadiumsForm()
        {
            InitializeComponent();

            // NEW: Modern styling
            ApplyModernStyling();

            txtid.TextChanged += txtid_TextChanged;
            LoadStadiums();

            // FIX: Calls UIHelper instead of local duplicate Placeholder method
            UIHelper.SetPlaceholder(txtname,     "Stadium Name");
            UIHelper.SetPlaceholder(txtcapacity, "Capacity");
            UIHelper.SetPlaceholder(txtcity,     "City");
            UIHelper.SetPlaceholder(txtid,       "ENTER STADIUM ID");
            txtid.ForeColor = System.Drawing.Color.Black;
        }

        private void ApplyModernStyling()
        {
            this.BackColor = UIHelper.SurfaceColor;
            this.Font      = new System.Drawing.Font("Segoe UI", 9f);

            UIHelper.StyleGrid(dataGridViewStadiums);

            UIHelper.StyleButton(btnAdd,    UIHelper.SuccessColor);
            UIHelper.StyleButton(btnUpdate, UIHelper.PrimaryAccent);
            UIHelper.StyleButton(btnDelete, UIHelper.DangerColor);
            UIHelper.StyleButton(btnBack,   System.Drawing.Color.FromArgb(108, 117, 125));
        }

        private void LoadStadiums()
        {
            try
            {
                var stadiums = StadiumRepository.GetAllStadiums();
                dataGridViewStadiums.DataSource = stadiums;

                // FIX: StadiumId was visible as a raw FK — now hidden
                if (dataGridViewStadiums.Columns["StadiumId"] != null)
                    dataGridViewStadiums.Columns["StadiumId"].Visible = false;

                // NEW: Friendly column headers
                if (dataGridViewStadiums.Columns["StadiumName"] != null)
                    dataGridViewStadiums.Columns["StadiumName"].HeaderText = "Stadium";
                if (dataGridViewStadiums.Columns["Capacity"] != null)
                    dataGridViewStadiums.Columns["Capacity"].HeaderText = "Capacity";
                if (dataGridViewStadiums.Columns["City"] != null)
                    dataGridViewStadiums.Columns["City"].HeaderText = "City";

                dataGridViewStadiums.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading stadiums: " + ex.Message,
                    "DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void txtid_TextChanged(object sender, EventArgs e)
        {
            if (!int.TryParse(txtid.Text, out int id)) return;

            var stadium = StadiumRepository.GetById(id);
            if (stadium != null)
            {
                txtname.Text     = stadium.StadiumName;
                txtcapacity.Text = stadium.Capacity.ToString();
                txtcity.Text     = stadium.City;

                txtname.ForeColor     = System.Drawing.Color.Black;
                txtcapacity.ForeColor = System.Drawing.Color.Black;
                txtcity.ForeColor     = System.Drawing.Color.Black;
                txtid.ForeColor       = System.Drawing.Color.Black;
            }
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            // FIX: Added validation — was raw int.Parse (crash if non-numeric)
            if (string.IsNullOrWhiteSpace(txtname.Text) || txtname.Text == "Stadium Name")
            {
                MessageBox.Show("Please enter a stadium name.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            if (!int.TryParse(txtcapacity.Text, out int capacity))
            {
                MessageBox.Show("Capacity must be a valid number.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                var s = new Stadium
                {
                    // FIX: Do NOT set StadiumId here — it is an IDENTITY column.
                    // The old code passed int.Parse(txtid.Text) which is wrong.
                    StadiumName = txtname.Text.Trim(),
                    Capacity    = capacity,
                    City        = txtcity.Text.Trim()
                };

                StadiumRepository.Add(s);

                // FIX: Added success message (was silent before)
                MessageBox.Show("Stadium added successfully!", "Success",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                LoadStadiums();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error adding stadium: " + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            if (dataGridViewStadiums.CurrentRow == null) return;

            if (!int.TryParse(txtid.Text, out int id) ||
                !int.TryParse(txtcapacity.Text, out int capacity))
            {
                MessageBox.Show("Stadium ID and Capacity must be valid numbers.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                var s = new Stadium
                {
                    StadiumId   = id,
                    StadiumName = txtname.Text.Trim(),
                    Capacity    = capacity,
                    City        = txtcity.Text.Trim()
                };

                StadiumRepository.Update(s);

                // FIX: Added success message + icon
                MessageBox.Show("Stadium updated successfully.", "Success",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                LoadStadiums();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error updating stadium: " + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            if (dataGridViewStadiums.CurrentRow == null) return;

            if (!int.TryParse(txtid.Text, out int id))
            {
                MessageBox.Show("Please select a valid stadium first.", "Validation",
                    MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            var confirm = MessageBox.Show(
                "Are you sure you want to delete this stadium?",
                "Confirm Delete", MessageBoxButtons.YesNo, MessageBoxIcon.Question);

            if (confirm != DialogResult.Yes) return;

            try
            {
                StadiumRepository.Delete(id);

                // FIX: Added success message + icon
                MessageBox.Show("Stadium deleted.", "Deleted",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                LoadStadiums();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error deleting stadium: " + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void dataGridViewStadiums_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0) return;

            var row = dataGridViewStadiums.CurrentRow;
            txtid.Text     = row.Cells["StadiumId"].Value.ToString();
            txtname.Text   = row.Cells["StadiumName"].Value.ToString();
            txtcapacity.Text = row.Cells["Capacity"].Value.ToString();
            txtcity.Text   = row.Cells["City"].Value.ToString();

            txtid.ForeColor       = System.Drawing.Color.Black;
            txtname.ForeColor     = System.Drawing.Color.Black;
            txtcapacity.ForeColor = System.Drawing.Color.Black;
            txtcity.ForeColor     = System.Drawing.Color.Black;
        }

        private void btnBack_Click(object sender, EventArgs e) => this.Close();

        // FIX: Removed duplicate LoadStadiums() call from Load event —
        // the constructor already calls it, so this was a double DB hit on startup.
        private void StadiumsForm_Load(object sender, EventArgs e) { }

        private void ClearFields()
        {
            txtname.Clear();
            txtcapacity.Clear();
            txtcity.Clear();
            txtid.Clear();
        }
    }
}
